import { Course, ObservationEntry, Badge, SocietyEvent, CertificateSettings } from '../types/astronomy';

export const ADMIN_SECURITY_PASSWORD = 'AstroEdncAdmin';

export const DEFAULT_CERTIFICATE_SETTINGS: CertificateSettings = {
  societyName: 'ROYAL ASTRONOMICAL OBSERVATORY SOCIETY',
  facultyName: 'FACULTY OF CELESTIAL MECHANICS & DEEP SKY OBSERVATION',
  certificateTitle: 'Certificate of Scientific Merit',
  citationBody: 'Demonstrating calibrated telescope alignment, sensor signal reduction, astronomical chart interpretation, and observational logging rigor.',
  signatory1Name: 'Dr. Aris Thorne',
  signatory1Title: 'Director of Observatories',
  signatory2Name: 'Prof. Valerie Vance',
  signatory2Title: 'Executive Examination Board',
  sealText: 'VERIFIED',
  sealYear: '2026',
};

export const ALL_BADGES: Badge[] = [
  {
    id: 'badge_first_flight',
    name: 'Observatory Initiate',
    description: 'Enrolled in the Astronomy Society Academic LMS and completed initial fellowship profile.',
    icon: '🔭',
    category: 'honorary',
    rarity: 'Common'
  },
  {
    id: 'badge_astrophoto_master',
    name: 'Astrophotography Pioneer',
    description: 'Mastered optical backfocus, camera sensor cooling, and polar alignment curriculum.',
    icon: '📸',
    category: 'course',
    rarity: 'Rare'
  },
  {
    id: 'badge_cartographer',
    name: 'Deep Sky Cartographer',
    description: 'Completed constellation mapping and celestial coordinate system mastery track.',
    icon: '🌌',
    category: 'course',
    rarity: 'Rare'
  },
  {
    id: 'badge_planetary_scientist',
    name: 'Planetary Geologist',
    description: 'Completed planetary observational science and lunar terminator analysis track.',
    icon: '🪐',
    category: 'course',
    rarity: 'Rare'
  },
  {
    id: 'badge_radio_astronomer',
    name: 'Radio Wave Voyager',
    description: 'Detected 21cm neutral hydrogen emissions and decoded galactic rotation curves.',
    icon: '📡',
    category: 'course',
    rarity: 'Epic'
  },
  {
    id: 'badge_quiz_ace',
    name: 'Astrophysical Quiz Ace',
    description: 'Scored 100% accuracy on an official academic course examination.',
    icon: '🎯',
    category: 'quiz',
    rarity: 'Legendary'
  },
  {
    id: 'badge_perseids_2026',
    name: 'Perseid Meteor Watcher',
    description: 'Participated in the Society 2026 Perseids Zenith Hourly Rate (ZHR) Observation Campaign.',
    icon: '☄️',
    category: 'event',
    rarity: 'Rare'
  },
  {
    id: 'badge_lunar_eclipse',
    name: 'Umbra Eclipse Scout',
    description: 'Recorded live spectroscopic photometric measurements during the Total Lunar Eclipse event.',
    icon: '🌑',
    category: 'event',
    rarity: 'Epic'
  },
  {
    id: 'badge_jwst_briefing',
    name: 'Deep Field Researcher',
    description: 'Attended the live Webb Space Telescope high-redshift galaxy symposium.',
    icon: '✨',
    category: 'event',
    rarity: 'Legendary'
  }
];

export const INITIAL_EVENTS: SocietyEvent[] = [
  {
    id: 'event_perseids_2026',
    title: 'Perseid Meteor Shower All-Night Sky Watch',
    date: 'August 12, 2026',
    time: '21:00 - 04:00 UTC',
    location: 'High-Altitude Dark Sky Reserve (Bortle 1) & Virtual Stream',
    description: 'Annual peak of the Perseid meteor stream generated by Comet 109P/Swift-Tuttle. Members log visual counts, radiant angles, and fireball magnitudes.',
    targetObject: 'Perseid Radiant (Constellation Perseus)',
    badgeId: 'badge_perseids_2026',
    badgeName: 'Perseid Meteor Watcher',
    badgeIcon: '☄️',
    registeredMembers: ['usr_001']
  },
  {
    id: 'event_lunar_eclipse',
    title: 'Total Lunar Eclipse Photometry Campaign',
    date: 'October 18, 2026',
    time: '23:30 - 03:45 UTC',
    location: 'Global Observatory Network & Remote Sensor Feed',
    description: 'Coordinated multi-wavelength photometer calibration as the Moon passes entirely through Earth\'s dark umbral shadow.',
    targetObject: 'Lunar Umbra (Danjon Scale L=2)',
    badgeId: 'badge_lunar_eclipse',
    badgeName: 'Umbra Eclipse Scout',
    badgeIcon: '🌑',
    registeredMembers: []
  },
  {
    id: 'event_jwst_symposium',
    title: 'JWST Early Universe Galaxy Clusters Symposium',
    date: 'November 05, 2026',
    time: '18:00 - 20:30 UTC',
    location: 'Society Main Auditorium & Live Audio Stage',
    description: 'Keynote presentation reviewing spectroscopic signatures of redshift z > 11 galaxies and primordial star clusters.',
    targetObject: 'SMACS J0723.3-7327 Gravitational Lens',
    badgeId: 'badge_jwst_briefing',
    badgeName: 'Deep Field Researcher',
    badgeIcon: '✨',
    registeredMembers: []
  }
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 1,
    title: 'Introduction to Astrophotography',
    description: 'Master equipment calibration, optical backfocus, sensor cooling, and polar alignment to capture high-contrast deep sky objects.',
    category: 'Imaging & Hardware',
    level: 'Introductory',
    leadAstronomer: {
      name: 'Dr. Elena Rostova',
      affiliation: 'High-Altitude Observatory',
      callsign: 'AST-882'
    },
    learningSubjects: [
      'Optical Backfocus & Sensor Spacing (55mm)',
      'Dark, Flat & Bias Frame Calibration',
      'Equatorial Mount Drift & Polar Alignment',
      'Narrowband vs Broadband Sensor Stacking'
    ],
    quiz: {
      courseId: 1,
      title: 'Astrophotography Calibration & Optical Alignment Exam',
      passingScore: 70,
      questions: [
        {
          id: 'q1_1',
          question: 'What is the standard backfocus distance required from the rear thread of most field flatteners and coma correctors to the camera sensor?',
          options: ['35mm (± 5mm)', '55mm (± 0.5mm)', '85mm (± 2mm)', '105mm (± 1mm)'],
          correctIndex: 1,
          explanation: '55mm is the de facto astronomical standard backfocus spacing established by T-ring adapters and flattener lenses.'
        },
        {
          id: 'q1_2',
          question: 'What is the primary scientific purpose of acquiring "Dark Frames" during calibration?',
          options: [
            'To compensate for optical vignetting and sensor dust donuts',
            'To subtract thermal noise, fixed pattern noise, and hot pixels from long exposures',
            'To calibrate sky background light pollution gradients',
            'To increase the ISO or analogue sensor gain'
          ],
          correctIndex: 1,
          explanation: 'Dark frames are captured at identical exposure times and temperatures with the telescope capped to model and subtract sensor thermal dark current.'
        },
        {
          id: 'q1_3',
          question: 'Why must an equatorial telescope mount have its Polar Axis aligned with the Earth\'s rotational axis?',
          options: [
            'To prevent optical field rotation during long exposure imaging',
            'To eliminate gravitational sagging of the primary mirror',
            'To filter atmospheric air turbulence near the horizon',
            'To automatically focus the primary optical train'
          ],
          correctIndex: 0,
          explanation: 'Because Earth rotates on its axis, tracking with an equatorial mount pointing at the celestial pole keeps stars perfectly circular without rotating the field of view.'
        }
      ]
    },
    lessons: [
      {
        id: 101,
        title: 'Camera Sensors, Telescope T-Rings & Backfocus',
        duration: '15 mins',
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        description: 'Detailed breakdown of CMOS vs CCD quantum efficiency, matching pixel pitch to focal length, and achieving critical 55mm sensor backfocus.',
        targetObject: 'M42 Orion Nebula',
        coordinates: {
          ra: '05h 35m 17.3s',
          dec: '-05° 23′ 28″',
          constellation: 'Orion'
        },
        keyTakeaways: [
          'Backfocus distance must be calibrated to within ±0.5mm for flat focal field correction',
          'Gain settings should target lowest read noise while preserving full-well capacity',
          'Thermoelectric cooling delta maintains dark current reduction at -10°C ambient'
        ],
        resources: [
          { name: 'Sensor_Pixel_Scale_Calculator.pdf', type: 'PDF', size: '1.2 MB' },
          { name: 'Optical_Train_Spacers_Guide.pdf', type: 'PDF', size: '2.4 MB' }
        ]
      },
      {
        id: 102,
        title: 'Polar Alignment with Equatorial Mounts',
        duration: '22 mins',
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        description: 'Step-by-step drift alignment, platesolving polar routines, and correcting altitude/azimuth mechanical errors to prevent star trailing.',
        targetObject: 'Polaris (Alpha Ursae Minoris)',
        coordinates: {
          ra: '02h 31m 49.1s',
          dec: '+89° 15′ 51″',
          constellation: 'Ursa Minor'
        },
        keyTakeaways: [
          'Polar alignment error under 30 arcseconds enables 5-minute unguided sub-exposures',
          'Drift alignment star on meridian isolates azimuth error; eastern star isolates altitude error',
          'Periodic error correction (PEC) training counteracts worm gear imperfections'
        ],
        resources: [
          { name: 'Polar_Drift_Alignment_Checksheet.pdf', type: 'PDF', size: '850 KB' }
        ]
      }
    ]
  },
  {
    id: 2,
    title: 'Deep Sky & Constellation Mapping',
    description: 'Master the celestial coordinate system (Right Ascension and Declination) and locate Messier and NGC objects with star-hopping techniques.',
    category: 'Celestial Mechanics',
    level: 'Intermediate',
    leadAstronomer: {
      name: 'Prof. Marcus Chen',
      affiliation: 'Royal Astronomical Society',
      callsign: 'RAS-412'
    },
    learningSubjects: [
      'Right Ascension & Declination Coordinate Systems',
      'Messier & NGC Deep Sky Star-Hopping',
      'Epoch Precession & Sidereal Time Slewing',
      'Bortle Scale Light Pollution Mitigation'
    ],
    quiz: {
      courseId: 2,
      title: 'Celestial Coordinate Systems & Catalog Examination',
      passingScore: 70,
      questions: [
        {
          id: 'q2_1',
          question: 'Right Ascension (RA) is customarily measured along the celestial equator in what primary units?',
          options: [
            'Degrees, arcminutes, and arcseconds (0° to 360°)',
            'Hours, minutes, and seconds (0h to 24h)',
            'Meters and Astronomical Units (AU)',
            'Parsecs and Light Years'
          ],
          correctIndex: 1,
          explanation: 'RA is expressed in hours, minutes, and seconds, matching Earth’s 24-hour sidereal rotational cycle.'
        },
        {
          id: 'q2_2',
          question: 'Which historical catalogue contains 110 prominent deep-sky objects including the Andromeda Galaxy (M31) and Crab Nebula (M1)?',
          options: ['Messier Catalogue', 'Caldwell Catalogue', 'Hipparcos Catalogue', 'Kepler Catalogue'],
          correctIndex: 0,
          explanation: 'Charles Messier compiled the list of 110 astronomical objects in the 18th century so comet hunters would not mistake them for comets.'
        },
        {
          id: 'q2_3',
          question: 'If a celestial object has a Declination of exactly +90° 00\' 00", where in the sky is it situated?',
          options: [
            'Directly on the Celestial Equator',
            'Directly at the North Celestial Pole',
            'At the observer\'s Zenith regardless of latitude',
            'Along the Ecliptic plane'
          ],
          correctIndex: 1,
          explanation: 'Declination is celestial latitude: 0° is the celestial equator, +90° is the North Celestial Pole, and -90° is the South Celestial Pole.'
        }
      ]
    },
    lessons: [
      {
        id: 201,
        title: 'Reading Star Charts, RA and Declination',
        duration: '18 mins',
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        description: 'Understanding celestial coordinates, epoch precession (J2000 vs J2026), hour angles, and converting sidereal time into telescope slews.',
        targetObject: 'Messier 31 (Andromeda Galaxy)',
        coordinates: {
          ra: '00h 42m 44.3s',
          dec: '+41° 16′ 09″',
          constellation: 'Andromeda'
        },
        keyTakeaways: [
          'Right Ascension increases eastward from the vernal equinox point in Aries',
          'Declination ranges from -90° (South Celestial Pole) to +90° (North Celestial Pole)',
          'Earth axial precession shifts coordinate grids by approximately 50.3 arcseconds per year'
        ],
        resources: [
          { name: 'Planisphere_Reading_Card.pdf', type: 'PDF', size: '3.1 MB' }
        ]
      }
    ]
  },
  {
    id: 3,
    title: 'Planetary Science & Lunar Geology',
    description: 'Explore high-resolution planetary imaging techniques, atmospheric dispersion correctors (ADC), and analyzing lunar maria and impact craters.',
    category: 'Solar System',
    level: 'Introductory',
    leadAstronomer: {
      name: 'Dr. Sarah Al-Mansoor',
      affiliation: 'Planetary Science Institute',
      callsign: 'PSI-094'
    },
    learningSubjects: [
      'Lucky Imaging & High Frame Rate Planetary Video',
      'Atmospheric Dispersion Correctors (ADC)',
      'Lunar Maria & Basaltic Crater Topography',
      'Jupiter & Saturn Ring Dynamics'
    ],
    quiz: {
      courseId: 3,
      title: 'Lunar Geology & Planetary Observation Exam',
      passingScore: 70,
      questions: [
        {
          id: 'q3_1',
          question: 'What geological material constitutes the dark plains (maria) visible on the Earth\'s Moon?',
          options: [
            'Liquid water oceans covered with fine carbon dust',
            'Ancient basaltic lava flows that flooded large impact basins',
            'Iron-nickel meteoritic debris pulverization',
            'High-albedo anorthosite crystalline crust'
          ],
          correctIndex: 1,
          explanation: 'The lunar maria are vast basaltic volcanic plains formed by ancient volcanic eruptions after heavy asteroid bombardment.'
        },
        {
          id: 'q3_2',
          question: 'What is the purpose of using an Atmospheric Dispersion Corrector (ADC) when imaging planets like Jupiter or Mars near the horizon?',
          options: [
            'To counteract the prism-like chromatic refraction of Earth\'s atmosphere',
            'To magnify the image like a Barlow lens',
            'To block ultraviolet sunlight from destroying telescope optics',
            'To increase the frame rate of CMOS planetary cameras'
          ],
          correctIndex: 0,
          explanation: 'Earth\'s atmosphere acts like a prism, splitting white planet light into red and blue fringe halos. An ADC utilizes opposing optical prisms to cancel this dispersion.'
        }
      ]
    },
    lessons: [
      {
        id: 301,
        title: 'Lucky Imaging & High Frame Rate Video Stacking',
        duration: '20 mins',
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        description: 'Capture thousands of uncompressed video frames at 120 FPS using high-speed USB3 planetary sensors, discarding blurry atmospheric turbulence.',
        targetObject: 'Jupiter & Galilean Moons',
        coordinates: {
          ra: '03h 05m 12s',
          dec: '+16° 42′ 00″',
          constellation: 'Aries'
        },
        keyTakeaways: [
          'Atmospheric "seeing" cells fluctuate every 5 to 10 milliseconds',
          'AutoStakkert quality ranking isolates the sharpest 10% of raw video frames',
          'Planetary derotation algorithms prevent planetary blur during multi-minute sessions'
        ]
      }
    ]
  },
  {
    id: 4,
    title: 'Radio Astronomy & Pulsar Detection',
    description: 'Learn radio interferometry, 21-centimeter neutral hydrogen line analysis, and decoding periodic signals from rotating neutron stars.',
    category: 'Radio Astronomy',
    level: 'Advanced',
    leadAstronomer: {
      name: 'Dr. Vikram Patel',
      affiliation: 'Deep Space Communication Complex',
      callsign: 'DSN-64'
    },
    learningSubjects: [
      '21cm Neutral Hydrogen Line (1420 MHz) Detection',
      'Radio Horn Antenna & SDR Receiver Construction',
      'Galactic Spiral Arm Rotation Curves',
      'Pulsar Periodic Timing & Doppler Analysis'
    ],
    quiz: {
      courseId: 4,
      title: 'Radio Interferometry & Galactic Hydrogen Exam',
      passingScore: 70,
      questions: [
        {
          id: 'q4_1',
          question: 'The 21-centimeter emission line used to map the spiral structure of the Milky Way originates from which atomic process?',
          options: [
            'Spin-flip transition of neutral atomic hydrogen (H I)',
            'Ionization of carbon monoxide in stellar nurseries',
            'Nuclear fusion in the core of young O-type stars',
            'Radioactive decay of cobalt isotopes in supernovae'
          ],
          correctIndex: 0,
          explanation: 'The 21 cm line (1420.405 MHz) occurs when the electron in a neutral hydrogen atom flips its spin direction relative to the proton.'
        },
        {
          id: 'q4_2',
          question: 'Why are radio telescopes able to observe galactic structures obscured from optical telescopes?',
          options: [
            'Long radio waves penetrate interstellar dust clouds with negligible scattering',
            'Radio waves travel faster than optical light through the interstellar medium',
            'Radio receivers operate only in absolute vacuum environments',
            'Optical telescopes cannot resolve objects beyond 100 light years'
          ],
          correctIndex: 0,
          explanation: 'Interstellar dust particles are much smaller than 21cm radio wavelengths, allowing radio emissions to travel unimpeded through the dense galactic disk.'
        }
      ]
    },
    lessons: [
      {
        id: 401,
        title: 'Building a 1420 MHz Horn Antenna & SDR Receiver',
        duration: '26 mins',
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        description: 'Construct a backyard cantenna or pyramidal horn receiver and record neutral hydrogen Doppler frequency shifts along the galactic plane.',
        targetObject: 'Milky Way Galactic Arm (Cygnus Region)',
        coordinates: {
          ra: '20h 30m 00s',
          dec: '+40° 00′ 00″',
          constellation: 'Cygnus'
        },
        keyTakeaways: [
          'Hydrogen 21cm waves penetrate all interstellar optical dust clouds',
          'Doppler frequency shifts reveal rotation velocities of spiral arms',
          'Low-noise preamplifiers (LNA) near the feed horn prevent coaxial signal loss'
        ]
      }
    ]
  }
];

export const INITIAL_OBSERVATION_LOGS: ObservationEntry[] = [
  {
    id: 'OBS-2026-001',
    timestamp: '2026-09-24 22:45 UTC',
    target: 'Messier 42 (Great Orion Nebula)',
    catalogueId: 'NGC 1976',
    magnitude: 4.0,
    equipment: '8" Schmidt-Cassegrain (f/10) + IMX571 Color',
    skyCondition: 'Rural (Bortle 3-4)',
    notes: 'Trapezium cluster A, B, C, D stars resolved clearly. High ionization veil extending into M43.',
    verified: true
  },
  {
    id: 'OBS-2026-002',
    timestamp: '2026-09-25 01:15 UTC',
    target: 'Saturnian System & Titan',
    catalogueId: 'SOL-06',
    magnitude: 0.6,
    equipment: '102mm Triplet Apochromatic Refractor',
    skyCondition: 'Pristine (Bortle 1-2)',
    notes: 'Cassini division distinct all along ring ansae. Subtle equatorial temperate band visible on disk.',
    verified: true
  },
  {
    id: 'OBS-2026-003',
    timestamp: '2026-09-25 23:30 UTC',
    target: 'Messier 31 (Andromeda Galaxy)',
    catalogueId: 'NGC 224',
    magnitude: 3.44,
    equipment: '70mm Quadruplet Astrograph (f/4.8)',
    skyCondition: 'Suburban (Bortle 5-6)',
    notes: 'Prominent dust lanes visible across 2.5 degree field. Companion galaxy M32 and M110 both verified.',
    verified: true
  }
];

export const PRESET_ADMIN_LESSON_VIDEOS = [
  {
    title: 'James Webb Space Telescope Deep Field Imaging',
    duration: '18 mins',
    url: 'https://www.youtube.com/embed/1C_nuqpHND8',
    description: 'Infrared spectroscopy and gravitational lensing analysis from JWST NIRCam instrument.'
  },
  {
    title: 'Deep Sky Astrophotography Stacking Masterclass',
    duration: '25 mins',
    url: 'https://www.youtube.com/embed/g2qJ3r82K98',
    description: 'Step-by-step registration, rejection algorithms, and background extraction in Siril & PixInsight.'
  },
  {
    title: 'ESO Super Telescope Laser Guide Star System',
    duration: '14 mins',
    url: 'https://www.youtube.com/embed/p1Q4wN1vG68',
    description: 'How adaptive optics use artificial sodium stars in the mesosphere to cancel air blur.'
  }
];
